# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sanket Kumar Singh
email: sanketsingh2mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sanket Kumar Singh, sanketsingh2mail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanketkumarsinghiitkgp.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  sanketkumarsinghiitkgp

# Build settings
markdown: kramdown
